# Generated by Django 6.0 on 2025-12-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_person_age_remove_person_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ISBN',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='ari8mosEisagoghs',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
