# Generated by Django 6.0 on 2025-12-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_person_isbn_alter_person_ari8moseisagoghs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ISBN',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
